server.port=8080
server.servlet.context-path=/Recruits
server.tomcat.connection-timeout=10s

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSS
spring.jackson.time-zone=Asia/Bangkok
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
